# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'RafikiApp' do
pod 'Braintree'
pod 'Firebase'
pod 'Firebase/Messaging'
end

target 'RafikiAppTests' do

end

target 'RafikiAppUITests' do

end

